---
- name: Reading config
  ansible.builtin.include_vars:
    file: config.yml
    name: config

- name: Configuring Gitlab
  become: true
  block:
    - name: getting reverse proxy ip
      ansible.builtin.command: "dig {{ config.rev_proxy_domain }} +short"
      register: rev_proxy_res

    - name: /etc/gitlab/gitlab.rb
      ansible.builtin.template:
        src: gitlab.rb.j2
        dest: /etc/gitlab/gitlab.rb
        backup: true
        mode: 0600
        owner: root
      notify: gitlab-ctl reconfigure
