---
# - hosts: db-main
#   roles:
#     - mysql_common
#     - mysql_source
# - hosts: db-repl
#   roles:
#     - mysql_common
#     - mysql_replica

# - hosts: gitlab
#   roles:
#     - gitlab

- hosts: runner
  roles:
    - runner
# - hosts: www
#   roles:
#     - nginx

#- hosts: app
#  roles:
#    - wordpress
