---
- name: Reading config
  ansible.builtin.include_vars:
    file: config.yml
    name: config

- name: Checking if debconf already populated
  become: true
  ansible.builtin.debconf:
    name: mysql-server
  register: r

- name: Setting debconf variables
  # Ref. https://dev.mysql.com/doc/mysql-apt-repo-quick-guide/en/#repo-qg-apt-repo-non-insteractive
  no_log: true
  when: '"mysql-community-server/root-pass" not in r.current'
  become: true
  ansible.builtin.debconf:
    name: mysql-server
    question: "{{ item.question }}"
    value: "{{ item.value }}"
    vtype: "{{ item.vtype }}"
  loop:
    - {
        question: "mysql-community-server/root-pass",
        vtype: "password",
        value: "{{ config.mysql_root_password }}",
      }
    - {
        question: "mysql-community-server/re-root-pass",
        vtype: "password",
        value: "{{ config.mysql_root_password }}",
      }
    - {
        question: "mysql-community-server/remove-data-dir",
        vtype: "boolean",
        value: false,
      }
    - {
        question: "mysql-server/default-auth-override",
        vtype: "select",
        value: "caching_sha2_password",
      }
    - {
        question: "mysql-server/lowercase-table-names",
        vtype: "select",
        value: "Enabled",
      }

- name: Installing from repo
  block:
    - name: Installing GPG
      become: true
      ansible.builtin.apt:
        update_cache: true
        name: gpg
    - name: Copying GPG key
      ansible.builtin.copy:
        src: files/mysql_pubkey.asc
        dest: mysql_pubkey.asc
    - name: Import GPG key
      become: true
      ansible.builtin.apt_key:
        file: mysql_pubkey.asc
    - name: Add repo
      become: true
      ansible.builtin.apt_repository:
        repo: deb http://repo.mysql.com/apt/debian bullseye mysql-8.0
        state: present
    - name: Installing
      become: true
      block:
        - name: apt mysql-server
          become: true
          ansible.builtin.apt:
            update_cache: true
            name: mysql-server
        - name: apt python3-pymysql
          become: true
          ansible.builtin.apt:
            name: python3-pymysql

- name: Setting database for replication in mysqld.cnf
  become: true
  ansible.builtin.blockinfile:
    create: true
    path: "/etc/mysql/mysql.conf.d/mysqld.cnf"
    block: |
      binlog_do_db  = "{{ config.mysql_app_db }}"
      gtid_mode=ON
      enforce-gtid-consistency=ON
  notify:
    - Restart MySQL

- name: Create MySQL user for the application
  community.mysql.mysql_user:
    name: "{{ config.mysql_app_user }}"
    host: "{{ config.app_upstream }}"
    password: "{{ config.mysql_app_password }}"
    # GRANT ALL PRIVILEGES ON databasename.* TO "wordpressusername"@"hostname"
    priv: "{{ config.mysql_app_db }}.*:ALL"
    state: present
    login_user: root
    login_password: "{{ config.mysql_root_password }}"

- name: Create MySQL user for Grafana
  community.mysql.mysql_user:
    name: "{{ config.my_sql_grafana_user }}"
    host: "{{ config.monitoring_upstream }}"
    password: "{{ config.my_sql_grafana_user_password }}"
    priv: "*.*:PROCESS,REPLICATION CLIENT,SELECT"
    state: present
    login_user: root
    login_password: "{{ config.mysql_root_password }}"

- name: Ensure MySQL is running
  become: true
  ansible.builtin.service:
    name: mysql
    enabled: true
    state: restarted

- name: Create user for Node Exporter
  become: true
  ansible.builtin.user:
    state: present
    name: prometheus
    append: true
    create_home: false
    system: true
    shell: /bin/false
    groups:
      - prometheus

- name: Create MySQL user for Node Exporter
  community.mysql.mysql_user:
    name: my_sql_node_exporter_user
    host: "localhost"
    password: "{{ config.my_sql_grafana_user_password }}" # TODO: сделать свой.
    priv: "*.*:PROCESS,REPLICATION CLIENT,SELECT"
    state: present
    login_user: root
    login_password: "{{ config.mysql_root_password }}"

# Ref. https://mcs.mail.ru/docs/additionals/cases/cases-monitoring/case-mysql-exporter#
- name: Download mysqld_exporter
  ansible.builtin.unarchive:
    src: "https://github.com/prometheus/mysqld_exporter/releases/download/v0.14.0/mysqld_exporter-0.14.0.linux-amd64.tar.gz"
    remote_src: true
    dest: /tmp
    creates: /tmp/mysqld_exporter-0.14.0.linux-amd64/mysqld_exporter
- name: oOo
  become: true
  ansible.builtin.copy:
    src: /tmp/mysqld_exporter-0.14.0.linux-amd64/mysqld_exporter
    remote_src: true
    dest: /usr/local/bin
    group: prometheus
    owner: prometheus
    mode: 0755
- name: oOo
  become: true
  ansible.builtin.file:
    path: /usr/local/etc/.mysqld_exporter.cnf
    state: absent
- name: setting password for mysqld_exporter
  become: true
  ansible.builtin.blockinfile:
    create: true
    dest: /usr/local/etc/.mysqld_exporter.cnf
    group: prometheus
    owner: prometheus
    mode: 0400
    block: |
      [client]
      user=my_sql_node_exporter_user
      password="{{ config.my_sql_grafana_user_password }}"

- name: templating /etc/systemd/system/mysqld_exporter.service
  become: true
  ansible.builtin.template:
    src: "mysqld_exporter.service.j2"
    dest: "/etc/systemd/system/mysqld_exporter.service"
    backup: false
    mode: 0644
    owner: root
    group: root

- name: Ensure mysqld_exporter is running
  become: true
  ansible.builtin.service:
    name: mysqld_exporter.service
    enabled: true
    state: restarted
