---
- name: Reading config
  ansible.builtin.include_vars:
    file: config.yml
    name: config

- name: Install common parts of the monitoring stack
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - ssl-cert
    - apt-transport-https
    - software-properties-common
    - wget
    - adduser
    - libfontconfig1

# NOTE: as of 30.09.2022, Grafana repo is down.
#
# - name: Add Grafana repo key
#   become: true
#   ansible.builtin.get_url:
#     url: https://packages.grafana.com/gpg.key
#     dest: /usr/share/keyrings/grafana.key

# - name: Add Grafana repo
#   become: true
#   ansible.builtin.apt_repository:
#     repo: "deb [signed-by=/usr/share/keyrings/grafana.key] https://packages.grafana.com/oss/deb stable main"
#     state: present

- name: Download Grafana
  ansible.builtin.get_url:
    url: https://dl.grafana.com/oss/release/grafana_9.2.0~beta1_amd64.deb
    dest: /tmp
- name: Install Grafana from local file
  become: true
  ansible.builtin.apt:
    deb: /tmp/grafana_9.2.0~beta1_amd64.deb

- name: Configure Grafana
  become: true
  ansible.builtin.template:
    src: "grafana.ini.j2"
    dest: "/etc/grafana/grafana.ini"
    backup: true
    mode: 0644
    owner: root
- name: Configure Grafana user
  become: true
  ansible.builtin.user:
    name: grafana
    append: true
    groups:
      - ssl-cert
      - root

- name: Fix Grafana permissions
  become: true
  ansible.builtin.file:
    path: /usr/share/grafana
    mode: 0755

- name: Install monitoring stack
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - prometheus-alertmanager
    - prometheus

- name: Configure Prometheus
  become: true
  ansible.builtin.template:
    src: "prometheus.yml.j2"
    dest: "/etc/prometheus/prometheus.yml"
    backup: true
    mode: 0644
    owner: root

- name: Configure Alert Manager
  block:
    - name: oOo
      become: true
      ansible.builtin.copy:
        src: "alert_rules.yml"
        dest: "/etc/prometheus/alert_rules.yml"
        backup: true
        mode: 0644
        owner: root
    - name: oOo
      become: true
      ansible.builtin.template:
        src: "alertmanager.yml.j2"
        dest: "/etc/prometheus/alertmanager.yml"
        backup: true
        mode: 0644
        owner: root

- name: Start monitoring services
  become: true
  ansible.builtin.service:
    name: "{{ item }}"
    state: restarted
  loop:
    - prometheus
    - prometheus-node-exporter
    - grafana-server
    - prometheus-alertmanager
